"." m00 "point"
"," m01 "pixel"
"o" m02 "circle"
"v" m03 "triangle down"
"^" m04 "triangle up"
"<" m05 "triangle left"
">" m06 "triangle right"
"1" m07 "tri down"
"2" m08 "tri up"
"3" m09 "tri left"
"4" m10 "tri right"
"8" m11 "octagon"
"s" m12 "square"
"p" m13 "pentagon"
"P" m23 "plus (filled)"
"*" m14 "star"
"h" m15 "hexagon 1"
"H" m16 "hexagon 2"
"+" m17 "plus"
"x" m18 "x"
"X" m24 "x (filled)"
"D" m19 "diamond"
"d" m20 "thin diamond"
"|" m21 "vline"
"_" m22 "hline"

[".", ",", "o", "v", "^", "<", ">", "1", "2", "3", "4", "8", "s", "p", "P", "*", "h", "H", "+", "x", "X", "D", "d", "|", "_"]

["point", "pixel", "circle", "triangle down", "triangle up", "triangle left", "triangle right", "tri down", "tri up", "tri left", "tri right", "octagon", "square", "pentagon", "plus (filled)", "star", "hexagon 1", "hexagon 2", "plus", "x", "x (filled)", "diamond", "thin diamond", "vline", "hline"]